### ISSUE TITLE
Links for package authors

### ISSUE THREAD

**Issue by krlmlr** [cynkra/cynkratemplate#12]
Example: If Christoph is a package author, his name in the "Authors" list should be a hyperlink pointing to https://www.cynkra.com/about.html .

How do they do it in https://github.com/tidyverse/tidytemplate?

**Comment by benubah** [comment]
Please see https://github.com/cynkra/cynkratemplate/pull/14

**Comment by benubah** [comment]
This feature can be automatically applied by modifying lines https://github.com/r-lib/pkgdown/blob/master/R/build-home-authors.R#L146 and https://github.com/r-lib/pkgdown/blob/master/R/build-home-authors.R#L148 in the `pkgdown` package to:

`paste0("<a href='https://cynkra.com/about.html#",tolower(given),"'>", given, "</a>")`
and 
`paste0("<a href='https://cynkra.com/about.html#",tolower(given),"'>", given, " ", family, "</a>")` 

If we don't want to do this, we could stick with adding a `href` with `anchors` for all authors in the `_pkgdown.yml` file.

**Comment by krlmlr** [comment]
In dm I do it manually from:

https://github.com/cynkra/dm/blob/main/pkgdown/_pkgdown.yml#L197-L205

Can we specify an authors list in the template?

**Comment by krlmlr** [comment]
Probably not yet, need to tweak `as_pkgdown()` .

**Comment by maelle** [comment]
See https://github.com/cynkra/fledge/pull/239#discussion_r855314852 

> you can actually add common authors to cynkratemplate directly see e.g. https://github.com/tidyverse/tidytemplate/blob/c584a6e1b95df94d63070c760096d838a3eed937/inst/pkgdown/BS5/_pkgdown.yml#L21

**Comment by krlmlr** [comment]
@pat-s: Can you please help here?

**Comment by pat-s** [comment]
> "add new cynkra devs to cynkratemplate author list"

I am not fully in the loop here but I don't think we want every cynkra member to be added automatically as a common author, do we? But maybe I also misunderstand the comment - could you please clarify?

I see this more like an individual action once a contributions has happened - and not as a generic one when onboarding a new person?

**Comment by pat-s** [comment]
I can integrate this in our ansible onboarding workflow and make sure we have always a complete list of cynkra members there. 

I am not sure yet how we would handle leaving members as we don't want to remove them from all pkgs, do we? We should just remove the hyperlink then...or shall we leave the hyperlinks out at all?

**Comment by krlmlr** [comment]
Good point, I think it's still valid to remove the leaving members from this list. They remain as contributors in `DESCRIPTION`, it's only the pkgdown site that is affected here -- a link will be added.

**Comment by maelle** [comment]
> I am not sure yet how we would handle leaving members as we don't want to remove them from all pkgs, do we? We should just remove the hyperlink then...or shall we leave the hyperlinks out at all?

Why not add an hyperlink to their homepage in that case? Btw is there an offboarding list? :-)
