### ISSUE TITLE
Second menu row

### ISSUE THREAD

**Issue by krlmlr** [cynkra/cynkratemplate#15]
without a sticky menu first. The first row should match the original header row on the website, the second row should be the "normal" pkgdown header.

![Screenshot from 2021-05-20 08-29-40](https://user-images.githubusercontent.com/1741643/118931877-bb3bb100-b947-11eb-936a-a9051d82fae9.png)

**Comment by christophsax** [comment]
I like what RStudio does here: 

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/1390827/119011337-42fbdc80-b995-11eb-9749-3cb02eecc3a7.png">

I subtle logo that tells people where this is coming from. IMO, it is not a good idea to have our website mingled with the package menu.

**Comment by benubah** [comment]
Looks good too! Their menu is sticky also.

For cynkratemplate we already have the cynkra website's footer in-place. If we decide to use RStudio's approach above, the cynkratemplate footer could maybe contain links to "Consulting", "Open Source", etc

I'm happy with any approach that's acceptable :)

**Comment by krlmlr** [comment]
I'm no longer sure this is the best approach.
