### ISSUE TITLE
use BS5

### ISSUE THREAD

**Issue by maelle** [cynkra/cynkratemplate#16]
in particular it'd add a search bar

**Comment by maelle** [comment]
and a larger default font size would be nice IMHO :mag:

**Comment by krlmlr** [comment]
Is it compatible/included with our new framework?

**Comment by maelle** [comment]
I don't think the pkgdown website will completely use your new framework, but rather use the same font, colours. For rOpenSci's rotemplate, the footer is the same as the main website, but the rest simply imitates the style with Bootstrap variables for colours and font. At this point I think a similar strategy is the easiest one.

**Comment by maelle** [comment]
I thought about this again reg dm website :sweat_smile: (font size, search bar)

**Comment by krlmlr** [comment]
How can we best make use of https://github.com/cynkra/cynkraweb-assets?

**Comment by maelle** [comment]
To me the first thing to try would be to extract some of the variables from there (main colours, font name) and start a new template from scratch to see whether it makes the pkgdown websites look "cynkra-ish" enough.

Related to https://github.com/cynkra/cynkraweb/issues/422 as the work on this should make it easier to pinpoint what makes cynkra.com unique
