### ISSUE TITLE
analytics

### ISSUE THREAD

**Issue by maelle** [cynkra/cynkratemplate#17]
what kind of traffic analytics does cynkra use?

**Comment by pat-s** [comment]
plausible for cynkra.com, none for cynkratemplate (yet)

**Comment by pat-s** [comment]
Sounds good to me. @mbannert is managing the plausible account atm. Matt, can you coordinate with Maelle?

**Comment by mbannert** [comment]
sure, @maelle let's use cynkra mattermost to coordinate. I can set you up with the details for plausible.io .  If you prefer to you can also just send a calendar invite for a call.

**Comment by maelle** [comment]
@pat-s Which package(s) have a cynkra.com subdomain? I'm realizing not even dm does so maybe none yet? For testing we'd need one with such a subdomain so that it might be registered in plausible.

**Comment by maelle** [comment]
@mbannert ok!

**Comment by pat-s** [comment]
{dm} has a configured subdomain on the infra side, it just needs to be applied in the package's pkgdown config. I've closed the PR after 7 months without response (https://github.com/cynkra/dm/pull/818).

Besides, there's tv.cynkra.com and cynkrathis.cynkra.com. I am not aware of more though eventually there might be.

**Comment by mbannert** [comment]
I've thought of different (sub)domains, too. Might be a blocker w.r.t. to plausible license model, but I will look into this with @maelle (and the plausible team if necessary). They have been very hands on and responsive so far.

**Comment by pat-s** [comment]
(If we're planning to stay and extend plausible usage, we might wanna revisit self-hosting plausible?)

**Comment by mbannert** [comment]
@pat-s thanks for the reminder. I do think self-hosting is an option down the road. For now,  I figured that the plausible pricing solely depends on page views, not the number of websites (as long as you have below 50 sites) . The information was front and center, but only when you're logged out. Given the low price of the service and the we probably need at least two hours to get the helm going, I'd stick to the SaaS version for now. Let's reconsider when we run into limitations. 

FWIW if we were to put more effort into plausible, I'd like to look at their API.

**Comment by maelle** [comment]
TODO (for me) = document https://github.com/cynkra/cynkrathis/blob/e3d29b1e1f4683a30b7eae2c4d9f1a976527678a/pkgdown/_pkgdown.yml#L7 + that the package maintainer first needs to ask cynkra plausible owner to create a subdomain.
