### ISSUE TITLE
Host a copy of the Frutiger font on cynkra.github.io

### ISSUE THREAD

**Issue by krlmlr** [cynkra/cynkratemplate#20]
so that the preview works. Need to think about how to host so that it works from "everywhere".

**Comment by maelle** [comment]
How would that work reg the font licence?

**Comment by krlmlr** [comment]
We'll take care of the license.

**Comment by maelle** [comment]
fixed by https://github.com/cynkra/cynkratemplate/issues/22#issuecomment-1198312860
