### ISSUE TITLE
CORS problems

### ISSUE THREAD

**Issue by maelle** [cynkra/cynkratemplate#22]
Related to #20 

@pat-s is there something that needs to be changed in the S3 bucket to allow cynkra.github.io/ to access the font files?

**Comment by maelle** [comment]
Note that the site does not look bad with the wrong font IMHO so it's not mission critical

**Comment by pat-s** [comment]
I might need to have a look, though the Frutiger font is served at https://tv.cynkra.com/ which uses `cynkratemplate`. 

We might want to use the above domain structure, let me know if I should add a new subdomain for a package. You can then add a CNAME entry to the gh-pages branch.

**Comment by maelle** [comment]
Thanks! Right now is cynkra.github.io/cynkratemplate supposed to be able to use the font or does something need to be changed?

**Comment by pat-s** [comment]
Imo we don't need cynkra.github.io/cynkratemplate and could remove the `gh-pages` branch. {cynkratemplate} is only used as a pkgdown template, there is no added value having a public pkgdown page, isn't it?

We can still do local previews when working on the package, which is probably the prerferred way anyhow.

I don't know how things are conifgured atm OTOH but it might be the font is restricted to `*.cynkra.com` domains and therefore cynkra.github.io/cynkratemplate does not work.

**Comment by maelle** [comment]
But where we do PR previews, that happen via gh-pages too, is it bad we can't access the font?

Otherwise, understood, for a cynkra package to fully take advantage of cynkra branding it should live at a `*.cynkra.com` subdomain.

**Comment by krlmlr** [comment]
Baby steps.

1. cynkra.github.io/cynkratemplate will host the fonts
2. We will be able to refer to the fonts from other cynkra.github.io pages
3. Pages look good
4. We move to cynkra.com
5. (May never happen) We remove the gh-pages branch from cynkra.github.io/cynkratemplate

I haven't followed the entire thread, what have I missed?

**Comment by pat-s** [comment]
The `cynkratemplate` repo should not host the font sources as the fonts should not be publicly accessible.
We control access via CORS rules in our bucket.

Currently we have the following CORS policy set

```json
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "HEAD"
        ],
        "AllowedOrigins": [
            "https://cynkra.com",
            "https://*.cynkra.com",
            "file://*"
        ],
        "ExposeHeaders": [],
        "MaxAgeSeconds": 0
    }
]
```

I've now additionally whitelisted `"https://cynkra.github.io/*"` and https://cynkra.github.io/cynkratemplate/ now shows the frutiger fonts.

I've also updated the README instructions.

**Comment by maelle** [comment]
Thank you! What a change a font can make :smile_cat:

**Comment by krlmlr** [comment]
I don't see Frutiger on https://cynkra.github.io/cynkratemplate/.

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/1741643/183710909-d534274b-433e-4663-a0d1-5e5256cd1d37.png">

**Comment by krlmlr** [comment]
The Frutiger font is shown as soon as I disable CORS checking in the browser. Are the new CORS rules still valid?

**Comment by pat-s** [comment]
My fault. Works now.
