### ISSUE TITLE
Apply to all cynkra packages

### ISSUE THREAD

**Issue by krlmlr** [cynkra/cynkratemplate#31]
@maelle: Can you please add more items to this list:

- [x] https://github.com/cynkra/dm/pull/1640, preview: https://cynkra.github.io/dm/dev/
- [x] https://github.com/cynkra/fledge/pull/568, preview: https://cynkra.github.io/fledge/dev/
- [x] https://github.com/cynkra/cynkrathis/pull/45, preview: https://cynkrathis.cynkra.com/dev/
- [x] https://github.com/cynkra/munch/pull/63, preview: https://cynkra.github.io/munch/ (no dev? https://github.com/cynkra/munch/issues/64)
- [x] https://github.com/cynkra/tv/pull/28

**Comment by maelle** [comment]
Packages that are already all set

- https://github.com/cynkra/indiedown

**Comment by maelle** [comment]
Note that the plausible part will be included but not work before the package has a cynkra.com subdomain (cc @mbannert )

**Comment by maelle** [comment]
@krlmlr for all packages of http://cynkra.r-universe.dev/ui#packages I've now opened a PR or requested access or seen cynkratemplate was already correctly in use.

**Comment by krlmlr** [comment]
Thanks. Can you please update the links in the issue description?

**Comment by maelle** [comment]
Related: https://github.com/cynkra/cynkrathis/issues/47

**Comment by krlmlr** [comment]
@christophsax: Would you like to review the new pkgdown sites, linked from the issue description?

**Comment by maelle** [comment]
Also note @pat-s opened two issues #34 #33 -- I could tackle a bunch of those at once based on feedback. :slightly_smiling_face:

**Comment by krlmlr** [comment]
@christophsax: Would you like to gloss over these pkgdown sites? Merging now, so that the changes stay permanent.

- [ ] https://cynkra.github.io/dm/dev/
- [ ] https://cynkra.github.io/fledge/dev/
- [ ] https://cynkra.github.io/munch/

**Comment by krlmlr** [comment]
Still might need a tweak in dm, but good by and large.
