### ISSUE TITLE
Colors for hovers and active items

### ISSUE THREAD

**Issue by pat-s** [cynkra/cynkratemplate#33]
Would be good to align colors to "cynkrablue" across the theme. It might be that "cynkrablue" won't be a good choice for all instances but to me the light purple doesn't match well with "cynkrablue".

Here are some suggestions:

![image](https://user-images.githubusercontent.com/8430564/197012940-9e3bce6c-58e7-4103-ac34-5ff1b5b5397c.png)

![image](https://user-images.githubusercontent.com/8430564/197013046-bceedf3c-08cc-4e7e-aa43-881c95419f09.png)

**Comment by maelle** [comment]
what light blue are you suggesting? good point in any case, thank you :blue_book:

**Comment by pat-s** [comment]
In https://server-manual.cynkra.com I used `#005f7e`.
