### ISSUE TITLE
menu style tweaks

### ISSUE THREAD

**Issue by christophsax** [cynkra/cynkratemplate#4]
<img width="283" alt="image" src="https://user-images.githubusercontent.com/1390827/85252571-6011ed80-b45c-11ea-94f5-f74a66001033.png">

Could we have:

- The logo fixed: dot is too big (as on cynkra.com) 
- The font of the 'reference' non-italic, as on the right?
- Perhaps all menu fonts capitalized, as on cynkra.com (no strong opinion here)
- Have you tried to have the menu without the shadow, as on cynkra.com, and a bit taller? I think the shadow is a non-flat element which we don't use otherwise. It may look a bit cleaner without it. But then there may be also too much white then.

**Comment by pat-s** [comment]
Reference was only by mistake in the left group.

The left group is aimed to contain the "devel/release" switches (which are not avail yet for tv).
See https://dm.pat-s.me/dev/ for an example.

> Have you tried to have the menu without the shadow, as on cynkra.com, and a bit taller?

Added the shadow and the smaller menu bar on purpose 🙈 
-> Removed the shadow.

> Perhaps all menu fonts capitalized, as on cynkra.com (no strong opinion here)

I find captitalized fonts somewhat aggressive, maybe we can get more opinions on this?

Have a look at the current appearance: https://cynkra.github.io/tv/

**Comment by christophsax** [comment]
Thanks! Perfectly happy with the look of https://cynkra.github.io/tv now. We can keep it like that, it doesn't need to be identical to cynkra.com.

A case could be made for caplitalized fonts in the case of a no border menu bar, as on cynkra.com. I still like it there, so accepting lowercase here doesn't mean that I agree on changing cynkra.com ;-)

**Comment by christophsax** [comment]
Ok, except the 'document' icon looks out of place:

<img width="157" alt="image" src="https://user-images.githubusercontent.com/1390827/85332231-def83c00-b4d7-11ea-9ce7-d3b4cd6f674b.png">

**Comment by pat-s** [comment]
> Ok, except the 'document' icon looks out of place:

You mean you want it to be removed entirely? Or is it misplaced?
Your screenshot also shows the old italic version, hence I am a bit confused.

Capitalized words on cynkra.com look ok - there, they are more subtle and the frutiger font is a bit more light than "Helvetica Neue" (the fallback font).
I just had a look at capitalized version in the pkgdown site and the thicker black font there looks a bit too aggressive imo.

**Comment by christophsax** [comment]
What is italic here?

<img width="335" alt="image" src="https://user-images.githubusercontent.com/1390827/85333161-67c3a780-b4d9-11ea-8794-74601b4bde18.png">

I see beautiful Frutiger everywhere. So why do we care about Helvetica Neue? (which probably exists on Macs only anyway?)

**Comment by pat-s** [comment]
Nothing italic, I was tired 😆 

See #5. Only Safari renders the frutiger font, other browsers block it due to upstream DNS issues in GH Pages.

**Comment by pat-s** [comment]
Menu bar titles are now upper case. Looks good with the frutiger font 👍

**Comment by pat-s** [comment]
@christophsax Good from your side? :)

**Comment by christophsax** [comment]
It looks great since a long time, but I would add:

```css
letter-spacing: 0.8px;
```

**Comment by pat-s** [comment]
Done.
