### ISSUE TITLE
Font used in pkgdown docs on cyncra.com (e.g. of the dm package) is blurry, at least in Edge and Firefox on Windows

### ISSUE THREAD

**Issue by jranke** [cynkra/cynkratemplate#45]
I only tested Edge and Firefox on Windows, but the font used in these browsers is blurry, which makes the documentation hard to read.

![image](https://github.com/cynkra/cynkratemplate/assets/3621037/e5fad030-bae0-476b-a544-cf70c7a500b1)

**Comment by maelle** [comment]
Thanks @jranke for reporting! 

Do you see any error message in the Web Developer Console? See for instance https://firefox-source-docs.mozilla.org/devtools-user/web_console/ and https://firefox-source-docs.mozilla.org/devtools-user/web_console/console_messages/index.html

**Comment by jranke** [comment]
In firefox on Linux, as I am using right now it is fine. Will check the Web Developer Console next week on Windows and report back.

**Comment by maelle** [comment]
Good that you at least get a nice reading experience on Linux :sweat_smile: (I use Firefox on Ubuntu too!) Thank you!

**Comment by jranke** [comment]
For some reason it's partly fixed when viewing with Firefox on Windows now, but still some text is blurred, e.g. the version number and the word `Author` in the sidebar to the right.
![image](https://github.com/cynkra/cynkratemplate/assets/3621037/63c10315-99c9-4f08-bc74-065686134633)

I do get a couple of "Invalid property name" warnings in the CSS analysis window of the Developer Tools, e.g.
![image](https://github.com/cynkra/cynkratemplate/assets/3621037/8963bae7-d464-4fa5-901c-7cd8f1aeba9d)
for the body tag of the page. But I do not know if this is related.

**Comment by jranke** [comment]
On edge, everything is still blurred
![image](https://github.com/cynkra/cynkratemplate/assets/3621037/52b83f6a-cff9-4069-90de-091272aaaff6)

**Comment by maelle** [comment]
@jranke thank you! In the console part of the console (the icon near Elemente I think), are there error messages?

**Comment by jranke** [comment]
Sorry for the delay, there are in fact error messages in Edge:

![image](https://github.com/cynkra/cynkratemplate/assets/3621037/be8b0b00-4ec4-4273-ad33-54a6e2e50369)

I would not think that they are related though.

**Comment by maelle** [comment]
@jranke I am so sorry for the delay! Does https://cynkratemplate.cynkra.com/ look better? Does https://cynkra.com look ok to you? I switched to using the same font rules as the main website.

**Comment by jranke** [comment]
Hi, https://cynkra.com looks nice in my Firefox on Windows, Edge does for some reason not work at the moment over here. The fonts on the cynkratemplate.com site look very basic, like arial or similar, but are definitely much more readable than https://dm.cynkra.com (all on Firefox at the moment).

**Comment by maelle** [comment]
@jranke note we're working on fonts, see #52 that hopefully will help. Thanks for your patience!

**Comment by talpitoo** [comment]
@maelle although the work under https://github.com/cynkra/cynkraweb/issues/662 unifies the fonts usage technically, i haven't tested in Edge. With the new font setup the most important part is to stick to the existing font weights: 300, 400 and 700 because any other value would be rendered with the browser's faux styles. cc. @christophsax In case we notice a font issue, this is the first thing we need to check, just a FYI.

**Comment by jranke** [comment]
Just to add that https://dm.cynkra.com is still blurry on Windows (Edge and Firefox). Could it be that the firewall of Agroscope is preventing the availability of your font?

**Comment by maelle** [comment]
@talpitoo can you please remind me what the problem is?

**Comment by talpitoo** [comment]
@maelle please see the "TL;DR" in my previous comment. I am not sure if you can resolve that build issue in the PR, if not, we might need devops help to proceed with https://github.com/cynkra/dm/pull/2199, cc. @christophsax

**Comment by maelle** [comment]
thanks for your patience :pray:

**Comment by krlmlr** [comment]
@jranke: Does it look better now?

**Comment by jranke** [comment]
Ah, finally it is nice, clean and readable! Thanks to all!
