### ISSUE TITLE
"Always suggest updating pull request branches" setting

### ISSUE THREAD

**Issue by maelle** [cynkra/cynkratemplate#49]
@pat-s could you please tweak the setting "Always suggest updating pull request branches" for this repo see https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-suggestions-to-update-pull-request-branches#managing-suggestions-to-update-a-pull-request-branch? Thank you!

(Unfortunately it doesn't seem to be possible to tweak this at the organization level, which would have been handy)

**Comment by pat-s** [comment]
done!

**Comment by maelle** [comment]
yay, thank you! That PR button is so useful :grin:
