### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by christophsax** [cynkra/cynkratemplate#5]
I see Frutiger in Safari but not in the other browsers. I force reloaded, so I don't think it is a caching issue.

It looks so much smoother, so it would be nice if we could get this running everywhere.

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/1390827/85371762-1810ca80-b531-11ea-9853-5b23d4413bb8.png">

**Comment by pat-s** [comment]
This is because of http://gitlab.private.cynkra.com/g/cynkra/public/cynkratemplate/merge_requests/1#note_9214.

It might work directly when we switch to the cynkra DNS instead of relying on GH Pages.
Could you create a CNAME entry for tv.cynkra.com to cynkra.github.io in the AWS DNS settings?

**Comment by christophsax** [comment]
Let's do this together at some point. 

Or let's set up cynkra.com deployment first. We just need to deploy these pages the same way as the website.

**Comment by pat-s** [comment]
> Or let's set up cynkra.com deployment first.

I could do this via https://github.com/marketplace/actions/github-action-for-s3_website. See the secrets which would be needed for this.

We can do this also together if you prefer this 🙂

**Comment by pat-s** [comment]
@christophsax I fear this will get forgotten and therefore the template won't be used although we are already almost finished.

Can we schedule a day after your vacation for this? 🙂 
I don't think we need more than one hour for this.

**Comment by pat-s** [comment]
Fixed in 4ce8344a9e8b587db164f2af8a2fe00c3c1609bf.

Also the fonts are now hosted on a Exoscale S3 bucket.
I'll try to make the switch for the website next.

cc @christophsax @krlmlr
