### ISSUE TITLE
Implement use_cynkra_favicon()

### ISSUE THREAD

**Issue by krlmlr** [cynkra/cynkratemplate#6]
so that it's easy to add a pkgdown icon.

Also `use_cynkra_pkgdown()` that sets up everything, maybe later.

**Comment by pat-s** [comment]
Not sure, this is just a c/p action and would require the favicon files to live in a centralized place.

**Comment by krlmlr** [comment]
They already live in this repo?

**Comment by krlmlr** [comment]
Can we maybe use them directly from this package if the template is active, without copying over?

**Comment by pat-s** [comment]
I think I tried that once for the mlr-org pkgdown template and it did not work.

**Comment by krlmlr** [comment]
I guess this means there's merit for a `use_xxx()` helper here?

**Comment by maelle** [comment]
If you put all the docs at say docs.cynkra.com/pkg-name then you only need the favicon to live in the source of docs.cynkra.com (then all paths inherit it). See for instance https://github.com/ropensci-docs/ropensci-docs.github.io

**Comment by krlmlr** [comment]
Can we still override favicons for individual packages?

**Comment by maelle** [comment]
Ah, no, that's a good point.

**Comment by maelle** [comment]
should I implement this function, @krlmlr?

**Comment by krlmlr** [comment]
@christophsax: Do we have a good favicon now?

**Comment by christophsax** [comment]
Style wise, the one in the website
<img width="119" alt="image" src="https://user-images.githubusercontent.com/1390827/195755817-9c7c4784-fe30-4f13-8eed-217550e1237b.png">
 is good.

**Comment by christophsax** [comment]
All logo materials should be in `marketing/logo`.

**Comment by krlmlr** [comment]
In which repo?

**Comment by christophsax** [comment]
https://gitea.cynkra.com/cynkra/marketing

**Comment by krlmlr** [comment]
@maelle: do you have access to https://gitea.cynkra.com/cynkra/marketing/src/branch/main/logo/favicon?
